### 7. 기술통계
NumPy는 다음과 같은 데이터 집합에 대해 간단한 통계를 계산하는 함수를 제공한다.  
이러한 값들을 통틀어 기술 통계(descriptive statistics)라고 한다.
- 데이터의 개수(count)
- 평균(mean, average)
- 분산(variance)
- 표준 편차(standard deviation)
- 최댓값(maximum)
- 최솟값(minimum)
- 중앙값(median)
- 사분위수(quartile)
  
예를 들어 다음과 같은 데이터 x가 있다고 하자.  
x={18,5,10,23,19,−8,10,0,0,5,2,15,8,2,5,4,15,−1,4,−7,−24,7,9,−6,23,−13}  
x를 이루는 숫자 하나하나를 수학 기호로는 x1,x2,⋯,xN처럼 표시한다. 위 예에서 x1=18, x2=5이다.  
  
NumPy에서는 이러한 데이터를 1차원 배열로 구현한다.

In [2]:
import numpy as np
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

#### 7.1 데이터의 개수
데이터의 개수는 len 명령으로 구할 수 있다.

In [3]:
len(x)  # 갯수

26

#### 7.2 샘플 평균
평균을 통계용어로는 샘플 평균(sample average, sample mean)이라고 한다.  
x 데이터에 대한 샘플 평균은 x¯라고 표시하며 다음과 같이 계산한다.   
이 식에서 N은 데이터의 개수이다.

In [5]:
np.mean(x)  # 평균

4.8076923076923075

#### 7.3 샘플 분산
샘플 분산(sample variance)은 데이터와 샘플 평균간의 거리의 제곱의 평균이다.  
샘플 분산이 작으면 데이터가 모여있는 것이고 크면 흩어져 있는 것이다.  
수학 기호로는 s2 이라고 표시하며 다음과 같이 계산한다.

In [6]:
np.var(x)  # 분산

115.23224852071006

In [7]:
np.var(x, ddof=1)  # 비편향 분산. 추후 공부하게 된다.

119.84153846153846

#### 7.4 샘플 표준편차
샘플 표준편차(sample standard variance)는 샘플 분산의 양의 제곱근 값이다. s이라고 표시한다.

In [8]:
np.std(x)  # 표준 편차

10.734628476137871

#### 7.5 최대값과 최소값
최대값(maximum)은 데이터 중에서 가장 큰 값을, 최소값(minimum)은 가장 작은 값을 의미한다.

In [9]:
np.max(x)  # 최댓값

23

In [10]:
np.min(x)  # 최솟값

-24

#### 7.6 중앙값
중앙값(median)은 데이터를 크기대로 정렬하였을 때 가장 가운데에 있는 수를 말한다.  
만약 데이터의 수가 짝수이면 가장 가운데에 있는 두 수의 평균을 사용한다.

In [11]:
np.median(x)  # 중앙값

5.0

#### 7.7 사분위수
사분위수(quartile)는 데이터를 가장 작은 수부터 가장 큰 수까지  
크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수를 말한다.  
각각 1사분위수, 2사분위수, 3사분위수라고 한다.  
1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%를 말한다.  
따라서 2사분위수는 중앙값과 같다.
  
때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 한다.  
1사분위수는 25% 백분위수와 같다.

In [12]:
np.percentile(x, 0)  # 최소값

-24.0

In [13]:
np.percentile(x, 25)  # 1사분위 수

0.0

In [14]:
np.percentile(x, 50)  # 2사분위 수

5.0

In [15]:
np.percentile(x, 75)  # 3사분위 수

10.0

In [16]:
np.percentile(x, 100)  # 최댓값

23.0

SciPy 패키지에는 여러가지 기술 통계 값을 한 번에 구해주는 describe 명령이 있다.

In [17]:
from scipy.stats import describe

In [18]:
describe(x)

DescribeResult(nobs=26, minmax=(-24, 23), mean=4.8076923076923075, variance=119.84153846153846, skewness=-0.4762339485461929, kurtosis=0.37443381660038977)

### 8. 난수 발생과 카운팅
파이썬을 이용하여 데이터를 무작위로 섞거나 임의의 수  
즉, 난수(random number)를 발생시키는 방법에 대해 알아본다.  
이 기능은 주로 NumPy의 random 서브패키지에서 제공한다.

#### 8.1 시드 설정하기
컴퓨터 프로그램에서 발생하는 무작위 수는 사실 엄격한 의미의 무작위 수가 아니다.  
어떤 특정한 시작 숫자를 정해 주면 컴퓨터가 정해진 알고리즘에 의해  
마치 난수처럼 보이는 수열을 생성한다. 이런 시작 숫자를 시드(seed)라고 한다.  
일단 생성된 난수는 다음번 난수 생성을 위한 시드값이 된다.  
따라서 시드값은 한 번만 정해주면 된다.  
시드는 보통 현재 시각등을 이용하여 자동으로 정해지지만 사람이 수동으로 설정할 수도 있다.  
특정한 시드값이 사용되면 그 다음에 만들어지는 난수들은 모두 예측할 수 있다.  
이 책에서는 코드의 결과를 재현하기 위해 항상 시드를 설정한다.  
  
파이썬에서 시드를 설정하는 명령은 seed이다. 인수로는 0과 같거나 큰 정수를 넣어준다.  

In [19]:
np.random.seed(0)

이렇게 시드를 설정한 후 rand 명령으로 5개의 난수를 생성해 보자.  
다른 난수 관련 명령어를 실행하지 말고 바로 다음 명령을 실행해야 한다.  
rand 명령은 0과 1사이의 난수를 발생시키는 명령으로 인수로 받은 숫자 횟수만큼 난수를 발생시킨다.

In [21]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

몇번 더 난수를 생성해보자. 사람이 예측할 수 없는 무작위 숫자가 나오는 것을 볼 수 있다.

In [23]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [24]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

이제 시드를 0으로 재설정하고 다시 난수를 발생시켜 본다.

In [26]:
np.random.seed(0)

In [27]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [28]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [29]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

아까와 같은 숫자가 나오는 것을 확인할 수 있다.

#### 8.2 데이터의 순서 바꾸기
데이터의 순서를 바꾸려면 shuffle 명령을 사용한다.

In [30]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.random.shuffle(x)
x

array([3, 6, 4, 5, 2, 9, 7, 8, 1, 0])

#### 8.3 데이터 샘플링
이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것을 샘플링(sampling)이라고 한다.  
샘플링에는 choice 명령을 사용한다. choice 명령은 다음과 같은 인수를 가질 수 있다.  
  
numpy.random.choice(a, size=None, replace=True, p=None)  
  
- a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
- size : 정수. 샘플 숫자
- replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능
- p : 배열. 각 데이터가 선택될 수 있는 확률

In [32]:
np.random.choice(5, 5, replace=False)  # shuffle 명령과 같다.

array([1, 4, 0, 3, 2])

In [33]:
np.random.choice(5, 3, replace=False)  # 3개만 선택


array([2, 1, 3])

In [34]:
np.random.choice(5, 10)  # 반복해서 10개 선택

array([0, 4, 1, 4, 1, 2, 2, 0, 1, 1])

In [35]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])  # 선택 확률을 다르게 해서 10개 선택

array([0, 3, 3, 2, 2, 3, 3, 2, 0, 3], dtype=int64)

#### 8.4 난수 생성
NumPy의 random 서브패키지에는 난수를 생성하는 다양한 명령을 제공한다.  
그 중 가장 간단하고 많이 사용되는 것은 다음 3가지 명령이다.
- rand: 0부터 1사이의 균일 분포
- randn: 가우시안 표준 정규 분포
- randint: 균일 분포의 정수 난수
  
rand 명령은 0부터 1사이에서 균일한 확률 분포로 실수 난수를 생성한다.  
숫자 인수는 생성할 난수의 크기이다. 여러개의 인수를 넣으면 해당 크기를 가진 행렬을 생성한다.

In [36]:
np.random.rand(10)

array([0.95894927, 0.65279032, 0.63505887, 0.99529957, 0.58185033,
       0.41436859, 0.4746975 , 0.6235101 , 0.33800761, 0.67475232])

In [37]:
np.random.rand(3, 5)

array([[0.31720174, 0.77834548, 0.94957105, 0.66252687, 0.01357164],
       [0.6228461 , 0.67365963, 0.971945  , 0.87819347, 0.50962438],
       [0.05571469, 0.45115921, 0.01998767, 0.44171092, 0.97958673]])

randn 명령은 기댓값이 0이고 표준편차가 1인 가우시안 표준 정규 분포를 따르는 난수를 생성한다.  
인수 사용법은 rand 명령과 같다.

In [38]:
np.random.randn(10)

array([-0.30237513, -2.2244036 ,  0.72400636,  0.35900276,  1.07612104,
        0.19214083,  0.85292596,  0.01835718,  0.42830357,  0.99627783])

In [39]:
np.random.randn(3, 5)

array([[-0.49114966,  0.71267817,  1.11334035, -2.15367459, -0.41611148],
       [-1.07089699,  0.22113881, -1.12305712, -1.05075796,  1.01207905],
       [ 1.54371643, -0.40211489,  0.8647491 , -0.22686923,  0.81116027]])

randint 명령은 다음과 같은 인수를 가진다.  
  
numpy.random.randint(low, high=None, size=None)  
  
만약 high를 입력하지 않으면 0과 low사이의 숫자를,  
high를 입력하면 low와 high는 사이의 숫자를 출력한다. size는 난수의 숫자이다.

In [40]:
np.random.randint(10, size=10)

array([0, 4, 3, 6, 9, 8, 0, 8, 5, 9])

In [41]:
np.random.randint(10, 20, size=10)

array([10, 19, 16, 15, 13, 11, 18, 10, 14, 19])

In [42]:
np.random.randint(10, 20, size=(3, 5))

array([[16, 15, 17, 18, 18],
       [19, 12, 18, 16, 16],
       [19, 11, 16, 18, 18]])

#### 8.5 정수 데이터 카운팅
이렇게 발생시킨 난수가 실수값이면 히스토그램 등을 사용하여 분석하면 된다.  
히스토그램을 시각화 부분에서 나중에 자세히 설명한다.  
  
만약 난수가 정수값이면 unique 명령이나 bincount 명령으로 데이터 값을 분석할 수 있다.  
이 명령들은 random 서브패키지가 아니라 NumPy 바로 아래에 포함된 명령이다.  
  
unique 명령은 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력한다.  
return_counts 인수를 True 로 설정하면 각 값을 가진 데이터 갯수도 출력한다.

In [43]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [45]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [46]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [47]:
count

array([2, 2, 1], dtype=int64)

그러나 unique 명령은 데이터에 존재하는 값에 대해서만 갯수를 세므로  
데이터 값이 나올 수 있음에도 불구하고 데이터가 하나도 없는 경우에는 정보를 주지 않는다.  
예를 들어 주사위를 10번 던졌는데 6이 한 번도 나오지 않으면 이 값을 0으로 세어주지 않는다.  
  
따라서 데이터가 주사위를 던졌을 때 나오는 수처럼 특정 범위안의 수인 경우에는  
bincount에 minlength 인수를 설정하여 쓰는 것이 더 편리하다.  
이 때는 0 부터 minlength - 1 까지의 숫자에 대해 각각 카운트를 한다.  
데이터가 없을 경우에는 카운트 값이 0이 된다.

In [48]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)