#### 1. 길이가 10인 0-벡터를 만드세요.

In [3]:
import numpy as np
zero_vector = np.zeros(10)
print(zero_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 2. 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요. 

In [4]:
np.where(np.arange(10)==4, 1, 0)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 3. 10 부터 49까지의 값을 가지는 벡터를 만드세요. 

In [5]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 4. 위(3번) 벡터의 순서를 바꾸세요. 

In [7]:
np.arange(49, 9, -1)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요. 

In [8]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6. 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

In [14]:
a = np.array([1,2,0,0,4,0], int)
a[a != 0]

array([1, 2, 4])

In [23]:
b = np.where(a != 0)
b

(array([0, 1, 4], dtype=int64),)

#### 7. 3x3 단위 행렬(identity matrix)을 만드세요 

In [24]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8. 난수 원소를 가지는 3x3 행렬을 만드세요 

In [26]:
a = np.random.random(9).reshape(3, 3)
a

array([[0.03751702, 0.66498681, 0.52182689],
       [0.80359854, 0.54586276, 0.2137057 ],
       [0.27478222, 0.02584334, 0.37953649]])

#### 9. 위(8번)에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요. 

In [34]:
print(a[np.argmax(a)//3, np.argmax(a)%3], np.argmax(a))
print(a[np.argmin(a)//3, np.argmin(a)%3], np.argmin(a))

0.8035985360325474 3
0.025843344055520467 7


#### 10. 위(8번)에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [35]:
np.mean(a, axis = 1), np.mean(a, axis = 0)

(array([0.40811024, 0.52105567, 0.22672068]),
 array([0.37196593, 0.41223097, 0.37168969]))